apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config
data:
  DYNAMODB_ENDPOINT: "http://dynamodb-local:8000"
  AWS_REGION: "us-east-1"
  WALLETS_TABLE_NAME: "wallets"
  TRANSACTIONS_TABLE_NAME: "transactions"
